if [ -r ~/.bash_funcs ]; then
    source ~/.bash_funcs
fi

# less
alias less="less -mRXF"

# fix for sudo auto completion and PATH
#alias sudo='sudo -E env PATH=$PATH'

# diff
if command -v colordiff > /dev/null 2>&1; then
    alias diff='colordiff -r'
    alias diff2='colordiff -r --suppress-common-lines -y -p -d'
else
    alias diff='diff -r'
    alias diff2='diff -r --suppress-common-lines -y -p -d'
fi

# nvim
alias vim='nvim'
alias vimdiff='nvim -d'
export EDITOR=nvim

alias more='less'
alias mkdir='mkdir -p -v'

# ptt
alias ptt='ssh bbsu@ptt.cc'

# safty
alias cp='cp -i'
alias mv='mv -i'
if ! is_osx; then
    alias rm='rm -I'
else
    alias rm='rm -i'
fi

# error-proof
alias ..='cd ..'
alias cd..='cd ..'

# ls
if ! is_osx; then
    alias ls='ls -hF --time-style=long-iso -v --color=always'
else
    alias ls='ls -hF --time-style=long-iso -v -G'
fi
alias ll='ls -l'
alias la='ls -a'
alias lx='ll -X' # sort by extension
alias lz='ll -rS' # sort by size
alias lt='ll -rt' # sort by date

# grep
alias grep='grep --exclude-dir=\.git --exclude-dir=\.repo --exclude-dir=\.svn --color=always --binary-files=without-match'
alias grepc='grep --include="*.[c|h|cpp|cxx|hpp|s|S]"'

# tmux shortcuts
alias td='tmuxd.sh'
alias tk='tmuxk.sh'
alias tl='tmuxl.sh'
alias ttl='tmux-light.sh'
alias ttd='tmux-dark.sh'

# to lower process priority
if ! is_osx; then
    alias benice='nice -n19 ionice -c3'
else
    alias benice='nice -n19'
fi

# trash-cli
if ! is_osx; then
    alias trp='trash-put'
    alias trl='trash-list'
    alias tre='( benice trash-empty & ) > /dev/null 2>&1'
    alias trr='restore-trash'
else # is_osx
    alias trp='trash'
    alias trl='trash -l'
    alias tre='benice trash -e'
fi

# terminal notification
if is_linux; then
    alias kwarn='notify-send -u normal -i "dialog-warning" "Konsole" "Task completed"'
elif is_osx; then
    alias kwarn='terminal-notifier -title "iTerm" -message "Task Completed"'
fi

# local ccache for Android distribution
alias lccache="./prebuilts/misc/linux-x86/ccache/ccache"

# df
alias df='df -h'

# du
alias du='du -hd 1'

# find
alias fn='find . -name'
alias fp='find . -path'
alias fdn='find . -type d -name'
alias fdp='find . -type d -path'

# cscope
alias csr='cscope -R'

# grep
alias gp='grep -rn'
alias gpi='grep -rni'

# git
alias gs='git status --column'
alias gss='git status --untracked-files=no'
alias ga='git add'
alias gr='git reset'
alias grh='git reset --hard'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit'
alias gca='git commit -a'
alias gd='git diff'
alias gdc='git diff --cached'
alias go='git checkout'
alias gob='git checkout -b'
alias gcp='git cherry-pick'
alias gl='git log'
alias glp='git log -p'
alias glo='git log --oneline -10'
alias gloo='git log --oneline . | less'
alias gwc='git whatchanged'
alias gcd='git clean -dfx'
alias gfa='git fetch -p --all'
alias grb='git rebase'
alias grbi='git rebase -i'
alias gpo='git push origin'
alias gpof='git push origin -f'
alias ggcall='for dir in ./*; do (cd "$dir" && pwd && git gc ; cd ..); done'

#misc
alias da='dastyle.sh'
alias dc='dcheckpatch.sh'
alias ga='git add'

alias fda='dastyle.sh *.c include/*.h'
alias fdc='dcheckpatch.sh *.c include/*.h'
alias fga='git add *.c include/*.h'
