function fsource {
    if [ -f "$1" ]; then
        . "$1"
    fi
}

fsource /etc/profile

# path
export PATH=$PATH:~/dotfiles/scripts
#for trash-cli
export PATH=$PATH:~/.local/bin
#for homebrew
export PATH=/usr/local/sbin:$PATH

# bash parameters
export EDITOR=nvim
export HISTSIZE=100
export HISTFILESIZE=200000
export HISTCONTROL=erasedups
export HISTIGNORE='&:cd ~:cd ..:[bf]g:exit:h:history'
export PROMPT_COMMAND='history -a' #update history after each command

fsource ~/dotnvt/configs/bash_profile
fsource /etc/bashrc
