#!/bin/bash --login

export LANG='en_US.UTF-8'

# set PATH so it includes user's private bin if it exists
if [ -d ~/bin ] ; then
    PATH=~/bin:"${PATH}"
fi

if [ -r ~/.bash_profile ]; then
    . ~/.bash_profile
fi

exec /usr/bin/x-session-manager
