#!/bin/bash

find . -type f -name "*.pdf" -print0 | while IFS= read -r -d $'\0' file; do
    cp "$file" "$file.bk"
    qpdf --password=4866431001 --decrypt "$file.bk" "$file"
    rm -f "$file.bk"
done

