#!/bin/bash

source ~/.bash_funcs

CONF_PATH=$HOME/dotfiles/configs

rm -rf ~/.gitconfig
if is_nvt; then
	cp $CONF_PATH/gitconfig.nvt ~/.gitconfig
else
	cp $CONF_PATH/gitconfig ~/.gitconfig
fi

rm -rf ~/.gittemplate
cp $CONF_PATH/gittemplate ~/.gittemplate

rm -rf ~/.gitignore
cp $CONF_PATH/gitignore ~/.gitignore

rm -rf ~/.git-completion.bash
cp $CONF_PATH/git-completion.bash ~/.git-completion.bash

rm -rf ~/.tmux.conf
if is_tmux18; then
    cp $CONF_PATH/tmux-1.8.conf ~/.tmux.conf
fi
if is_tmux21; then
    cp $CONF_PATH/tmux-2.1.conf ~/.tmux.conf
fi
if is_tmux26; then
    cp $CONF_PATH/tmux-2.6.conf ~/.tmux.conf
fi

rm -rf ~/.bashrc
cp $CONF_PATH/bashrc ~/.bashrc

rm -rf ~/.bash_aliases
cp $CONF_PATH/bash_aliases ~/.bash_aliases

rm -rf ~/.bash_profile
cp $CONF_PATH/bash_profile ~/.bash_profile

rm -rf ~/.bash_funcs
cp $CONF_PATH/bash_funcs ~/.bash_funcs

rm -rf ~/.inputrc
cp $CONF_PATH/inputrc ~/.inputrc

rm -rf ~/.vimrc
cp $CONF_PATH/vimrc ~/.vimrc

rm -rf ~/.colordiffrc
cp $CONF_PATH/colordiffrc ~/.colordiffrc

rm -rf ~/.dircolors
cp $CONF_PATH/dircolors.ansi-dark ~/.dircolors

rm -rf ~/.config/user-dir.dirs
cp $CONF_PATH/user-dir.dirs ~/.config/

if ! is_osx; then
    rm -rf ~/.terminfo
    cp -r $CONF_PATH/terminfo ~/.terminfo
fi
