#!/bin/bash

source ~/.bash_funcs

CONF_PATH=$HOME/dotfiles/configs
SNAPSHOT=$HOME/dotfiles/nvim-snapshot

rm -rf ~/.config/nvim
cp -r $CONF_PATH/nvim ~/.config/

rm -rf ~/.local/share/nvim
mkdir -p ~/.local/share/nvim

if is_nvt; then
	cp -r $SNAPSHOT/site ~/.local/share/nvim/
fi
