#!/bin/bash

source ~/.bash_funcs

CONF_PATH=$HOME/dotfiles/configs
SNAPSHOT=$HOME/dotfiles/nvim-snapshot

rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
mkdir -p ~/.config/nvim
mkdir -p ~/.local/share/nvim/site

if is_nvt; then
	cp -r $SNAPSHOT/site ~/.local/share/nvim/site
fi

cp $CONF_PATH/init.lua ~/.config/nvim/init.lua
cp $CONF_PATH/ginit.vim ~/.config/nvim/ginit.vim
