#!/bin/bash

source ~/.bash_funcs

CONF_PATH=$HOME/dotfiles/configs

rm -rf ~/.config/nvim

if ! is_nvt; then
    cp -r $CONF_PATH/vim ~/.config/nvim
else
    cp -r $HOME/dotfiles/nvim-snapshot ~/.config/nvim
fi

cp $CONF_PATH/vimrc ~/.config/nvim/init.vim
cp $CONF_PATH/ginit.vim ~/.config/nvim/ginit.vim
