#!/bin/bash

function cu {
    pushd . > /dev/null
    if [ "${PWD}" != "$HOME" ]; then
        until [ -d .git -o -d .repo -o -d .svn -o "${PWD}" == "$HOME" ]; do
            cd ..
        done
    fi
    local new_pwd=`pwd`
    popd > /dev/null
    cd $new_pwd
}

cu

if [ -f kernel/kthread.c ]; then
    echo "Generate kernel cscope db..."
    ARCH=arm make cscope
else
    echo "Generate cscope db..."
    git ls-files | egrep -i "\.(c|h|cpp|cc)$" > "cscope.files"

    #find "$PWD" -name '*.[ch]' \
    #-o -name '*.java' \
    #-o -name '*properties' \
    #-o -name '*.cpp' \
    #-o -name '*.cc' \
    #-o -name '*.hpp' \
    #-o -name '*.py' \
    #-o -name '*.php' > "$cscope.files"

    #echo "Adding files to cscope db: $PWD/cscope.db ..."
    cscope -q -b -i "cscope.files"
fi

#export CSCOPE_DB="$PWD/cscope.out"
#echo "Exported CSCOPE_DB to: '$CSCOPE_DB'" 
