#android.htc.china.location.service
#com.android.CSDFunctionG
#com.android.backupconfirm
#com.android.bluetooth
#com.android.bluetoothmidiservice
#com.android.captiveportallogin
#com.android.certinstaller
#com.android.defcontainer
#com.android.documentsui
#com.android.externalstorage
#com.android.htmlviewer
#com.android.inputdevices
#com.android.keychain
#com.android.location.fused
#com.android.managedprovisioning
#com.android.mms.service
adb shell pm hide com.android.nfc
#com.android.pacprocessor
#com.android.phone
#com.android.providers.calendar
#com.android.providers.contacts
#com.android.providers.downloads
#com.android.providers.downloads.ui
#com.android.providers.media
#com.android.providers.settings
#com.android.providers.telephony
#com.android.providers.userdictionary
#com.android.proxyhandler
#com.android.server.telecom
#com.android.settings
#com.android.sharedstoragebackup
#com.android.shell
#com.android.smith
#com.android.statementservice
#com.android.stk
#com.android.systemui
#com.android.vending
#com.android.vpndialogs
#com.android.wallpapercropper
#com.dolby
#com.dsi.ant.server
#com.google.android.apps.docs
#com.google.android.apps.docs.editors.docs
#com.google.android.apps.docs.editors.sheets
#com.google.android.apps.docs.editors.slides
#com.google.android.apps.maps
#com.google.android.configupdater
#com.google.android.gms
#com.google.android.gsf
#com.google.android.gsf.login
#com.google.android.keep
#com.google.android.onetimeinitializer
#com.google.android.packageinstaller
#com.google.android.setupwizard
#com.google.android.syncadapters.calendar
#com.google.android.syncadapters.contacts
#com.google.android.talk
#com.google.android.webview
#com.google.android.youtube
#com.htc.CustomizationSetup
#com.htc.HTCSpeaker
#com.htc.Weather
#com.htc.WifiRouter
#com.htc.accessory
#com.htc.albumgp
#com.htc.android.htcloglevel
#com.htc.android.htcsetupwizard
#com.htc.android.locationpicker
#com.htc.android.mail
#com.htc.android.qxdm2sd
#com.htc.android.voicedictation
#com.htc.android.worldclock
#com.htc.autobot
#com.htc.autobot.cargps.provider
#com.htc.backupreset
#com.htc.calendar
#com.htc.camera2
#com.htc.captiveportallogin
#com.htc.checkinprovider
#com.htc.contacts
#com.htc.cs.identity
#com.htc.demoflopackageinstaller
#com.htc.dialerservice
#com.htc.dnatransfer
adb shell pm hide com.htc.dotmatrix
#com.htc.drawingboard
#com.htc.drive.activator
#com.htc.fingerprint
adb shell pm hide com.htc.flexnet
#com.htc.fmservice
#com.htc.framework
#com.htc.guide
#com.htc.home.personalize
#com.htc.htccompressviewer
#com.htc.htcpowermanager
#com.htc.launcher
#com.htc.locationservicessetting
#com.htc.lockscreen
#com.htc.mirrorlinkserver
#com.htc.mobiledata
#com.htc.oobe.advantage
#com.htc.photoenhancer
#com.htc.power_caoffload
#com.htc.provider.CustomizationSettings
#com.htc.providers.htcmessage
#com.htc.resetnotify
#com.htc.sdm
#com.htc.sense.easyaccessservice
#com.htc.sense.hsp
#com.htc.sense.ime
#com.htc.sense.ime.langpack.mindic
#com.htc.sense.ime.langpack.mvie
#com.htc.sense.ime.langpack.phwr
#com.htc.sense.ime.langpack.tbasic
#com.htc.sense.ime.langpack.tvalueadd
#com.htc.sense.mms
#com.htc.sense.socialnetwork.facebook
#com.htc.soundrecorder
#com.htc.theme.font.helvetica
#com.htc.theme.font.xingothic_en
#com.htc.theme.font.yuen
#com.htc.uibc
#com.htc.updater
#com.htc.usage
#com.htc.video
#com.htc.widget.weatherclock
#com.htc.wifi.pingtool
#com.htc.wifidisplay
#com.qti.service.colorservice
#com.qualcomm.cabl
#com.qualcomm.location
#com.qualcomm.qti.tetherservice
#com.qualcomm.sta
#com.qualcomm.timeservice
#com.quicinc.cne.CNEService
adb shell pm hide org.simalliance.openmobileapi.service
